// QUIZ HANDLER FOR PEP
//
// Conventions:
//
//  <form class="pep-quiz">
//    <label>
//      What color is my t-shirt?
//      <input type="radio" />Blue
//      <input type="radio" />Black
//      <input type="radio" x-pep-quiz-answer>Red
//    </label>
//  </form>
//
//  This is the minimal form. Submit button, close button, scoreboard will
//  all be generated by the Pep handler.
//
//  ... or ...
//
//   <form
//     class="pep-quiz"
//     x-pep-quiz-name="Quiz: The Greatest NASCAR Drivers of All Time"
//     x-pep-quiz-stylesheet="styles/nascar.css"
//   >
//     <fieldset>
//       <label>
//         In what year did <b>Richard Petty</b> win 10 NASCAR races in a row?
//         <input type="text" x-pep-quiz-answer="1967" />
//       </label>
//     </fieldset>
//     <fieldset>
//       <label>
//         Who is known as The Intimidator?
//         <select x-pep-quiz-answer="Dale Earnhardt Sr.">
//           <option></option>
//           <option>Dale Earnhardt Sr.</option>
//           <option>Tony Stewart</option>
//         </select>
//       </label>
//       <button x-pep-send="submit">Check your answers!</button>
//       <button x-pep-send="close">Close</button>
//     </fieldset>
//   </form>
//
//  If you have multiple questions, each question MUST appear in its
//  own fieldset. This example also loads an external stylesheet into the
//  popup, and has explicit buttons for close and submit actions.
//
//  On submit, each fieldset is assigned an attribute of
//  x-pep-quiz-marked="correct|incorrect".
//
//   ... or ...
//
//   <form class="pep-quiz">
//     <fieldset>
//       <p>Who designed the original JavaScript language?</p>
//       <div x-pep-send="select submit">Brandon Eichmann</div>
//       <div x-pep-send="select submit">Rudolf Wøllinger</div>
//       <div x-pep-send="select submit" x-pep-quiz-answer>Brendan Eich</div>
//       <div x-pep-send="select submit">Rudolph Wöllinger</div>
//     </fieldset>
//     <div class="if-pep-quiz pep-quiz-scoreboard">
//       You scored <span x-pep-data="quiz-score-correct"></span>
//       out of <span x-pep-data="quiz-score-total"></span>!
//     </div>
//   </form>
//
//   This example has a defined scoreboard, overriding the generated one.
//   The submit button is supplied by the Pep handler here.
//
//   This also shows how you can turn any HTML element into a multiple choice
//   option, by making it send 'select' to the quiz. It will be given a
//   class of pep-quiz-selected when it is clicked.
//
//
// Actions:
//
// These can be sent from anywhere:
//  - trigger
//  - reset-all
//  - submit
//  - close
//  - jump(#) | start (ie, jump(0))
//
// These *may only* be sent from within a fieldset:
//  - check
//  - next
//  - prev
//  - reset
//
Pep.Handler.Quiz = function (pepdoc) {
  pepdoc.each('.pep-quiz', function (quizForm) {
    // We replace the quiz form with a button that acts as a proxy
    // to invoke the actual quiz form inside an iframe. We can tell
    // whether it's the actual quiz form using the 'x-pep-quiz-state'
    // attribute flag.
    if (quizForm.getAttribute('x-pep-quiz-state') != 'live') {
      Pep.Handler.Quiz.Proxy(pepdoc, quizForm);
    } else {
      Pep.Handler.Quiz.Form(pepdoc, quizForm);
    }
  });
}


Pep.Handler.Quiz.Proxy = function (pepdoc, quizForm) {
  var p = {};


  function initialize() {
    p.doc = quizForm.ownerDocument;
    p.quizId = quizForm.id || ('pep-quiz-standalone-'+(new Date()).getTime());
    p.quizHTML = getQuizHTML();
    p.quizStylesheet = quizForm.getAttribute('x-pep-quiz-stylesheet');
    p.quizButton = replaceQuizForm();
    if (pepdoc.sendersFor(p.quizButton, 'trigger').length) {
      p.quizButton.style.display = 'none';
    } else {
      p.quizButton.setAttribute('x-pep-send', 'trigger');
    }
    delete quizForm;
  }


  function getQuizHTML() {
    var cloneElement = quizForm.cloneNode(true);
    cloneElement.setAttribute('x-pep-quiz-state', 'live');
    cloneElement.id = p.quizId;
    var surrogate = p.doc.createElement('div');
    surrogate.appendChild(cloneElement);
    return surrogate.innerHTML;
  }


  function replaceQuizForm() {
    // Create the button:
    var btn = p.doc.createElement('input');
    btn.type = 'button';
    btn.value = 'Take the quiz!';
    // Turn the button into a proxy for triggering this quiz:
    quizForm.parentNode.insertBefore(btn, quizForm);
    quizForm.parentNode.removeChild(quizForm);
    btn.id = quizForm.id;
    btn.xPepTarget = { 'trigger': trigger };
    return btn;
  }


  function quizLoaded(subdoc) {
    Pep.attach(subdoc);
  }


  function trigger(sender) {
    Pep.Generate.popupIframe(
      sender,
      { fragment: p.quizHTML, stylesheet: p.quizStylesheet },
      { className: 'pep-popup-quiz', closeBtn: true },
      quizLoaded
    );
  }


  initialize();
}


Pep.Handler.Quiz.Form = function (pepdoc, quizForm) {
  var p = {};
  var k = {
    ANSWER_ATTR: 'x-pep-quiz-answer',
    SELECT_KLS: 'pep-quiz-selected'
  };


  function initialize() {
    var doc = quizForm.ownerDocument;
    p.qSel = '#'+quizForm.id;
    p.name = quizForm.getAttribute('x-pep-quiz-name') || 'Quiz';

    // Convert "submit" inputs into senders.
    quizForm.onsubmit = function (evt) {
      submit();
      evt.preventDefault();
    }
    pepdoc.find('input[type="submit"]', function (submit) {
      submit.setAttribute('x-pep-send', 'submit');
    });

    // Create a submit button if it doesn't exist
    if (!pepdoc.sendersFor(quizForm, 'submit').length) {
      var submit = doc.createElement('button');
      submit.innerHTML = 'Check your answers';
      submit.setAttribute('x-pep-send', 'submit');
      quizForm.appendChild(submit);
      // NB: should append to final fieldset if there are fieldsets and the
      // final fieldset does not have a 'next' sender.
    }

    // Create data bindings for scoreboard
    p.scoreboard = pepdoc.find(p.qSel+' .pep-quiz-scoreboard');
    if (!p.scoreboard) {
      p.scoreboard = doc.createElement('div');
      p.scoreboard.className = 'pep-quiz-scoreboard';
      p.scoreboard.innerHTML = [
        'You scored <span x-pep-data="quiz-score-correct"></span>',
        'out of <span x-pep-data="quiz-score-total"></span>'
      ].join('\n');
      quizForm.appendChild(p.scoreboard);
    }
    p.scoreboard.style.display = 'none';

    // Kick this thing off.
    goToCard(0);
  }


  function goToCard(cursor) {
    p.scoreboard.style.display = 'none';
    var cards = pepdoc.each(p.qSel+' fieldset');
    if (!cards.length) {
      return;
    } else if (cursor < 0) {
      p.cardCursor = 0;
    } else if (cursor >= cards.length) {
      p.cardCursor = cards.length - 1;
      return submit();
    } else {
      p.cardCursor = cursor;
    }
    focus(cards[p.cardCursor]);
  }


  function submit() {
    checkAnswers();
    p.scoreboard.style.display = 'block';
    focus(p.scoreboard);
  }


  function reset() {
    p.score = { total: 0, correct: 0 };
    pepdoc.each('.'+k.SELECT_KLS, deselectAnswer);
    // TODO: revert values of all fields
  }


  function checkAnswers() {
    p.score = { total: 0, correct: 0 };
    pepdoc.each('['+k.ANSWER_ATTR+']', checkAnswer);
    publishScore();
  }


  function checkAnswer(field) {
    p.score.total += 1;
    var qElem = questionForField(field);

    var correctIf = function (bool) {
      p.score.correct += bool ? 1 : 0;
      qElem.setAttribute('x-pep-quiz-marked', bool ? 'correct' : 'incorrect');
    }
    if (hasSelectTrigger(field)) {
      correctIf(field.classList.contains(k.SELECT_KLS));
    } else if (field.type == 'radio' || field.type == 'checkbox') {
      pepdoc.each(p.qSel+' [name="'+field.name+'"]:checked', selectAnswer);
      correctIf(field.checked);
    } else {
      selectAnswer(field);
      var val = field.value.trim();
      var ans = field.getAttribute(k.ANSWER_ATTR).trim();
      // Will be case-insensitive if answer is all-lowercase.
      if (ans.match(/^[^A-Z]*$/)) { val = val.toLowerCase(); }
      correctIf(val === ans);
    }
  }


  function questionForField(field) {
    var qElem = field.parentNode;
    while (qElem && qElem != quizForm && qElem.tagName != 'FIELDSET') {
      qElem = qElem.parentNode;
    }
    return qElem;
  }


  function selectAnswer(field) {
    field.classList.add(k.SELECT_KLS);
    if (field.parentNode.tagName == 'LABEL') {
      selectAnswer(field.parentNode);
    }
  }


  function deselectAnswer(field) {
    field.classList.remove(k.SELECT_KLS);
  }


  function hasSelectTrigger(field) {
    var msg = field.getAttribute('x-pep-send');
    if (typeof msg == 'string') {
      var actions = msg.split(/\s/);
      while (actions.length) {
        if (actions.shift() == 'select') { return true; }
      }
    }
  }


  // FIXME: How do we scope this data to the scoreboard for this quiz if
  // there are multiple quizzes in the component? We could use id, but what
  // do we do for quizzes without ids?
  //
  // One option: we could scope on id -- eg: quiz-score-correct-quizNascar
  // -- then we look for x-pep-data attributes that have unscoped labels
  // and modify them to be scoped by the provided or generated id (ie, we
  // will turn x-pep-data="quiz-score-correct" into
  // x-pep-data="quiz-score-correct-quizNascar").
  //
  // This is nice because it requires zero changes in Pep core. But it is
  // harder for x-pep-data-if expressions... And besides, this seems like
  // it will be a common problem, requiring a standard solution.
  //
  function publishScore() {
    //console.log("%s: %s out of %s", p.name, p.score.correct, p.score.total);
    Pep.setData({
      'quiz-score-correct': p.score.correct,
      'quiz-score-total': p.score.total
    });
  }


  function focus(elem) {
    var kls = 'pep-quiz-focus';
    pepdoc.each(p.qSel+' .'+kls, function (fg) { fg.classList.remove(kls); });
    if (elem) {
      elem.classList.add(kls);
      elem.ownerDocument.defaultView.scrollTo(0, 0);
    }
  }


  /* The actions */

  quizForm.xPepTarget = {
    submit: submit,


    reset: function () {
      reset();
      goToCard(0);
    },


    close: function () {
      // TODO
      alert('Quiz action: close');
    },


    jump: function (sender, receiver, arg) { goToCard(parseInt(arg, 10)); },


    start: function () { goToCard(0); },


    select: function (sender) {
      var qElem = questionForField(sender);
      qElem.removeAttribute('x-pep-quiz-marked');
      var fields = qElem.querySelectorAll('.'+k.SELECT_KLS);
      for (var i = 0, ii = fields.length; i < ii; ++i) {
        deselectAnswer(fields[i]);
      }
      selectAnswer(sender);
    },


    check: function (sender) {
      // TODO
      alert('Quiz action: check');
    },


    next: function (sender) { goToCard(p.cardCursor + 1); },


    previous: function (sender) { goToCard(p.cardCursor - 1); }
  };

  initialize();
}


Pep.register('quiz', Pep.Handler.Quiz);
